#!/bin/bash

apt-get -qy update && apt-get -qy install unzip || true

cd build/android
mkdir -p gradle
wget https://services.gradle.org/distributions/gradle-6.9.3-bin.zip
unzip -d gradle gradle-6.9.3-bin.zip
