name: android build
on:
  - push
jobs:
  build:
    name: build android apps
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2020.3.36f1-android-1
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: inspect
        run: |
          which unity
          echo $JAVA_HOME
          which gradle
