name: android build
on:
  - push
jobs:
  build:
    name: build android apps
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2020.3.36f1-android-1
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: inspect
        run: |
          echo "$UNITY_LICENSE" > UnityLicenseFile.ulf
          unity-editor -logFile -quit -manualLicenseFile UnityLicenseFile.ulf
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-project
          path: build/android
