name: android build
on:
  - push
jobs:
  build:
    name: build android apps
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2020.3.36f1-android-1
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: activate unity license
        run: ./ci/android/activate
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: export android project
        run: ./ci/android/export

      - name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-project
          path: build/android
